// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADU3vxcZ0Lg1UBfvV8WN9bhEddaIw-GjE',
    appId: '1:245116336855:web:18f593ec7e27ad98fc8e92',
    messagingSenderId: '245116336855',
    projectId: 'flutter-project-sigi',
    authDomain: 'flutter-project-sigi.firebaseapp.com',
    storageBucket: 'flutter-project-sigi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDMAxhkUhtoec0Xhn-2W8fBY78ri9uUg',
    appId: '1:245116336855:android:ff09a4d3b2d83e2ffc8e92',
    messagingSenderId: '245116336855',
    projectId: 'flutter-project-sigi',
    storageBucket: 'flutter-project-sigi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzKZIvgCi-Bt8lYhl7i-KfE3fnYSP6xL4',
    appId: '1:245116336855:ios:f0ebc78509d88a4ffc8e92',
    messagingSenderId: '245116336855',
    projectId: 'flutter-project-sigi',
    storageBucket: 'flutter-project-sigi.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

}